name: Cypress tests
on:
  pull_request:
    branches:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.5.0-chrome97-ff96
      options: --user 1001
    name: E2E on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm install
      - name: Cypress run
        id: cypresstest
        run: |
          npm config set color fales
          OUTPUT1=`npm run test:smoke| tail -50 | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g"`
          echo "OUTPUT1"
          echo "OUTPUT<<EOF" >> &GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        continue_on_error: true
      - run: |
          npm run e2e:reports
      - name: print output
        run: echo "${{ env.OUTPUT }}"
      - name: store results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test reports
          path: test-reports